#!/bin/sh
#
# PROVIDE: startvm
# REQUIRE: LOGIN FILESYSTEMS
# BEFORE: securelevel
# KEYWORD: nojail shutdown

# ----

. /etc/rc.subr

name="startvm"
rcvar=startvm_enable

start_cmd="startvm_start"
stop_cmd="startvm_stop"

# ----

startvm_cleanup()
{
	installdir=$(dirname $startvm_binary)
	systemcfg=$installdir/system.cfg

	if [ -f $systemcfg ] ; then
		. $systemcfg
	else
		return
	fi

	if [ -e $RTDIR/id ] ; then
		pgrep bhyve >/dev/null 2>&1

		if [ $? -eq 1 ] ; then
			rm -f $RTDIR/*
		fi
	fi
}

startvm_start()
{
	if [ $startvm_cleanup == "YES" ] ; then
		startvm_cleanup
	fi

	echo -n "Starting Bhyve VMs: "

	for _v in ${startvm_list} ; do
		echo -n "$_v "
		$startvm_binary run $_v
	done

	echo
}

startvm_stop()
{
	echo -n "Stopping Bhyve VMs: "
	
	for _v in ${startvm_list} ; do
		echo -n "$_v "
		$startvm_binary halt $_v
	done

	echo
}

# ----

load_rc_config $name
: ${startvm_enable="NO"}
: ${startvm_binary="/usr/opt/startvm/bin/startvm"}
: ${startvm_cleanup="YES"}

cmd="$1"

if [ $# -gt 0 ]; then
	shift
fi

if [ -n "$*" ]; then
	startvm_list="$*"
fi

run_rc_command "$cmd"

